#!/usr/bin/env python3
"""task-admission.py — Validate task admission metadata before queue entry.

Checks that required admission fields are present and non-empty.
Stricter for auto-generated tasks (creation_mode != manual).

Usage:
    python3 task-admission.py <task_file>          # validate, exit 0=pass 1=fail
    python3 task-admission.py <task_file> --json    # output JSON result
    python3 task-admission.py <task_file> --strict  # require all fields even for manual

Import:
    from importlib.util import spec_from_file_location, module_from_spec
    # or just: validate_admission(filepath) -> dict

architecture_scope enforcement matrix (current policy, 2026-04-14):
    Hard fail (missing = rejected):
        - impact-seeded     (auto-generated by brain-impact-evaluate)
        - codex-suggested   (auto-generated by codex)
        - signal-driven     (auto-generated by brain-signal-admit)
        - session-derived   (generated during a live session; structured classification required)
    Advisory only (missing = warning, not blocked):
        - manual            (human or agent session work)
        - follow-up         (spawned from another task)

    In all cases: an invalid value (not in VALID_ARCHITECTURE_SCOPES) is always
    a hard error regardless of creation_mode — typos erase the value of the field.

    Tightening manual/follow-up enforcement is a future decision, not implied by
    the current pass. When ready, add those modes to is_auto below.
"""

import json
import os
import re
import sys

# Fields required for ALL tasks
REQUIRED_FIELDS = ["created_by", "creation_mode", "authority_basis", "why_now"]

# Allowed values
VALID_CREATION_MODES = {"manual", "follow-up", "session-derived", "impact-seeded", "codex-suggested", "signal-driven"}
VALID_CREATED_BY = {"human", "claude-code", "brain-impact-evaluate", "codex", "brain-signal-admit"}
VALID_ARCHITECTURE_SCOPES = {
    "brain-core", "brain-module", "shared-infra",
    "governance-doc", "external-build", "experimental", "deprecation",
}
VALID_SCOPE_TAGS = {
    "adapter", "integration", "migration", "maintenance",
    "audit", "customer", "prototype",
}


def parse_scope_tags(raw):
    """Parse scope_tags from CSV or bracketed CSV frontmatter."""
    if not raw:
        return []
    cleaned = raw.strip()
    if cleaned.startswith("[") and cleaned.endswith("]"):
        cleaned = cleaned[1:-1].strip()
    if not cleaned:
        return []
    tags = []
    for part in cleaned.split(","):
        tag = part.strip().strip("'").strip('"')
        if tag:
            tags.append(tag)
    return tags


def extract_frontmatter(content):
    """Parse YAML-like frontmatter between --- markers."""
    lines = content.split("\n")
    if not lines or lines[0].strip() != "---":
        return {}
    fm_lines = []
    for line in lines[1:]:
        if line.strip() == "---":
            break
        fm_lines.append(line)
    else:
        return {}
    fields = {}
    for line in fm_lines:
        m = re.match(r'^(\w+):\s*"?([^"]*)"?\s*$', line)
        if m:
            fields[m.group(1)] = m.group(2).strip()
    return fields


def validate_admission(filepath, strict=False):
    """Validate admission metadata on a task file.

    Returns dict with:
        valid: bool
        errors: list of error strings
        warnings: list of warning strings
        fields: dict of parsed admission fields
    """
    result = {"valid": True, "errors": [], "warnings": [], "fields": {}}

    try:
        with open(filepath, "r") as f:
            content = f.read()
    except (OSError, IOError) as e:
        result["valid"] = False
        result["errors"].append(f"cannot read file: {e}")
        return result

    fm = extract_frontmatter(content)
    if not fm:
        result["valid"] = False
        result["errors"].append("no frontmatter found")
        return result

    # Extract admission fields
    for field in REQUIRED_FIELDS:
        val = fm.get(field, "").strip()
        result["fields"][field] = val

    creation_mode = result["fields"].get("creation_mode", "")
    is_auto = creation_mode in ("impact-seeded", "codex-suggested", "signal-driven", "session-derived")

    # Check required fields
    missing = []
    for field in REQUIRED_FIELDS:
        val = result["fields"].get(field, "")
        if not val or val.startswith("{{"):
            missing.append(field)

    if missing:
        if is_auto or strict:
            # Auto-generated tasks MUST have all admission fields
            result["valid"] = False
            result["errors"].append(
                f"missing required admission fields: {', '.join(missing)}"
            )
        else:
            # Manual/follow-up tasks: warn but don't block
            result["warnings"].append(
                f"missing admission fields (recommended): {', '.join(missing)}"
            )

    # Validate field values if present
    created_by = result["fields"].get("created_by", "")
    if created_by and created_by not in VALID_CREATED_BY and not created_by.startswith("{{"):
        result["warnings"].append(
            f"created_by '{created_by}' not in standard set: {sorted(VALID_CREATED_BY)}"
        )

    if creation_mode and creation_mode not in VALID_CREATION_MODES and not creation_mode.startswith("{{"):
        result["warnings"].append(
            f"creation_mode '{creation_mode}' not in standard set: {sorted(VALID_CREATION_MODES)}"
        )

    # Dependency validation: depends_on should reference an existing task
    depends_on = fm.get("depends_on", "").strip()
    if depends_on:
        brain_dir = os.environ.get("BRAIN_DIR", os.path.join(os.environ.get("HOME", ""), "brain"))
        tasks_dir = os.path.join(brain_dir, "brain", "ops", "tasks")
        dep_exists = (
            os.path.exists(os.path.join(tasks_dir, "queue", depends_on + ".md"))
            or os.path.exists(os.path.join(tasks_dir, "completed", depends_on + ".md"))
            or os.path.exists(os.path.join(tasks_dir, "active", depends_on + ".md"))
        )
        if not dep_exists:
            result["warnings"].append(
                f"depends_on '{depends_on}' not found in queue/active/completed"
            )
        result["fields"]["depends_on"] = depends_on

    # Related tasks (informational, no validation beyond format)
    related = fm.get("related", "").strip()
    if related:
        result["fields"]["related"] = related

    # architecture_scope: classification of what kind of work this is.
    # Invalid values are always rejected — typos erase the value of classification.
    # Missing: warn for manual/follow-up tasks, error for auto-generated.
    arch_scope = fm.get("architecture_scope", "").strip()
    if arch_scope:
        if arch_scope not in VALID_ARCHITECTURE_SCOPES:
            result["valid"] = False
            result["errors"].append(
                f"architecture_scope '{arch_scope}' not in allowed values: "
                f"{sorted(VALID_ARCHITECTURE_SCOPES)}"
            )
        result["fields"]["architecture_scope"] = arch_scope
    else:
        if is_auto or strict:
            result["valid"] = False
            result["errors"].append(
                "architecture_scope is required for auto-generated tasks — "
                f"allowed: {sorted(VALID_ARCHITECTURE_SCOPES)}"
            )
        else:
            result["warnings"].append(
                f"architecture_scope not set — consider classifying: {sorted(VALID_ARCHITECTURE_SCOPES)}"
            )

    # scope_tags: optional lightweight secondary nuance (comma-separated).
    scope_tags = fm.get("scope_tags", "").strip()
    if scope_tags:
        tags = parse_scope_tags(scope_tags)
        invalid_tags = [t for t in tags if t not in VALID_SCOPE_TAGS]
        if invalid_tags:
            result["valid"] = False
            result["errors"].append(
                f"scope_tags contains unknown values: {invalid_tags} "
                f"— allowed: {sorted(VALID_SCOPE_TAGS)}"
            )
        result["fields"]["scope_tags"] = ", ".join(tags)

    # execution_profile: if present, must match a known profile ID in execution-profiles.json.
    # An unknown profile ID is always a hard error — it means the routing table will silently
    # ignore the intent. Missing is allowed (not all tasks need a profile).
    exec_profile = fm.get("execution_profile", "").strip()
    if exec_profile:
        brain_dir = os.environ.get("BRAIN_DIR", os.path.join(os.environ.get("HOME", ""), "brain"))
        profiles_path = os.path.join(brain_dir, "brain", "ops", "execution-profiles.json")
        try:
            with open(profiles_path) as _pf:
                _profiles_data = json.load(_pf)
            known_profiles = {p["profile_id"] for p in _profiles_data.get("profiles", [])}
            if exec_profile not in known_profiles:
                result["valid"] = False
                result["errors"].append(
                    f"execution_profile '{exec_profile}' not found in execution-profiles.json "
                    f"— known: {sorted(known_profiles)}"
                )
        except (OSError, IOError, json.JSONDecodeError, KeyError) as _pe:
            result["warnings"].append(
                f"could not validate execution_profile '{exec_profile}': {_pe}"
            )
        result["fields"]["execution_profile"] = exec_profile

    # Soft warning: node: field is missing (fires for all tasks, not only title-matched ones)
    node_val = fm.get("node", "").strip()
    if not node_val:
        title = fm.get("title", "")
        nodes_dir = os.path.join(os.environ.get("BRAIN_DIR", os.path.join(os.environ.get("HOME", ""), "brain")), "nodes")
        try:
            known_nodes = [
                d for d in os.listdir(nodes_dir)
                if os.path.isdir(os.path.join(nodes_dir, d))
                and not d.startswith("_") and not d.startswith("example")
            ]
        except OSError:
            known_nodes = []
        title_lower = title.lower()
        matched = [n for n in known_nodes if n.replace("-", " ") in title_lower or n in title_lower]
        hint = f" (title suggests: '{matched[0]}')" if matched else ""
        result["warnings"].append(
            f"node: field is missing{hint} — set node: to enable infer-impact exclusion and scope routing"
        )

    return result


def main():
    if len(sys.argv) < 2:
        print("Usage: task-admission.py <task_file> [--json] [--strict]", file=sys.stderr)
        sys.exit(1)

    filepath = sys.argv[1]
    use_json = "--json" in sys.argv
    strict = "--strict" in sys.argv

    if not os.path.isfile(filepath):
        print(f"Error: file not found: {filepath}", file=sys.stderr)
        sys.exit(1)

    result = validate_admission(filepath, strict=strict)

    if use_json:
        json.dump(result, sys.stdout, indent=2)
        sys.stdout.write("\n")
    else:
        if result["valid"]:
            print(f"PASS: {os.path.basename(filepath)}")
            for w in result["warnings"]:
                print(f"  WARNING: {w}")
        else:
            print(f"FAIL: {os.path.basename(filepath)}")
            for e in result["errors"]:
                print(f"  ERROR: {e}")
            for w in result["warnings"]:
                print(f"  WARNING: {w}")

    sys.exit(0 if result["valid"] else 1)


def _run_tests():
    """Inline tests for execution_profile validation. Run: python3 task-admission.py --test"""
    import tempfile, os

    brain_dir = os.environ.get("BRAIN_DIR", os.path.join(os.environ.get("HOME", ""), "brain"))
    profiles_path = os.path.join(brain_dir, "brain", "ops", "execution-profiles.json")
    if not os.path.exists(profiles_path):
        print("SKIP: execution-profiles.json not found")
        return

    with open(profiles_path) as f:
        known = {p["profile_id"] for p in json.load(f).get("profiles", [])}
    valid_profile = next(iter(sorted(known)))  # pick first alphabetically

    def make_task(profile_line=""):
        return f"""---
task_id: TASK-TEST-001
title: "Test task"
node: "devops-tools"
status: queued
priority: P3
created_by: claude-code
creation_mode: manual
authority_basis: human-directed
why_now: "testing"
{profile_line}
---

# Test task
"""

    pass_count = 0
    fail_count = 0

    def check(label, content, expect_valid, expect_fragment=None):
        nonlocal pass_count, fail_count
        with tempfile.NamedTemporaryFile(mode='w', suffix='.md', delete=False) as f:
            f.write(content)
            f.flush()
            result = validate_admission(f.name)
            os.unlink(f.name)
        ok = result["valid"] == expect_valid
        if expect_fragment:
            needle_found = any(expect_fragment in e for e in result["errors"] + result["warnings"])
            ok = ok and needle_found
        status = "PASS" if ok else "FAIL"
        if ok:
            pass_count += 1
        else:
            fail_count += 1
            print(f"  {status}: {label}")
            print(f"    valid={result['valid']} errors={result['errors']} warnings={result['warnings']}")
        if ok:
            print(f"  {status}: {label}")

    check("no execution_profile → valid", make_task(), expect_valid=True)
    check("valid profile → valid", make_task(f'execution_profile: "{valid_profile}"'), expect_valid=True)
    check(
        "unknown profile → invalid",
        make_task('execution_profile: "not-a-real-profile-xyz"'),
        expect_valid=False,
        expect_fragment="not found in execution-profiles.json",
    )

    print(f"\nResults: {pass_count} passed, {fail_count} failed")
    return fail_count == 0


if __name__ == "__main__":
    if "--test" in sys.argv:
        ok = _run_tests()
        sys.exit(0 if ok else 1)
    main()
